/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package firebase.inappmessaging;

import com.google.firebase.inappmessaging.FirebaseInAppMessaging;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

@Kroll.module(name="TitaniumFirebaseInAppMessaging", id="firebase.inappmessaging")
public class TitaniumFirebaseInAppMessagingModule extends KrollModule
{
	// Methods

	@Kroll.method
	public void triggerEvent(String eventName)
	{
		FirebaseInAppMessaging.getInstance().triggerEvent(eventName);
	}
}
